# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9efa804237d86ec75e1f1751d148d9c053f39d49acafa08e62060e88714a6d45d3718a9f16b55f603b8229c542bf3fc14246f6add2cb1ad6ac8f92ae796f341a

test:
  secret_key_base: 97f657c17f1a33e0cf673ca2240b4b29c103a2a916cc0a3b6c142d2cdec7fb8828299f7981dd1cf5f021e1e3cf70cf66b82adf5f1e631b2c97d7e59a11db8c30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
